filebeat.inputs:
- type: filestream
  id: docker-container-logs 
  paths:
    - '/var/lib/docker/containers/*/*.log'
  parsers:
    - container:
        stream: all
        format: auto

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

setup.kibana:
  host: "kibana:5601"