servises:
  nexus:
    image: sonatype/nexus3:3.89.0-alpine
    container_name: nexus
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ./nexus-data:/nexus-data
    environment:
      - 'INSTALL4J_ADD_VM_PARAMS="-Xms1024m -Xmx1024m -XX:MaxDirectMemorySize=2703m"'

volumes:
  nexus-data: