global:
    scrape_interval: 15s

rule_files:
  - rules.yml

scrape_configs:
  - job_name: cadvision
    scrape_interval: 5s
    static_configs:
      - targets: ["cadvision:8080"]

  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets/*.json'


  - job_name: docker engine
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal"]

  - job_name: node exporter
    scrape_interval: 5s
    static_configs:
      - targets: ["node-exporter:9100"]

